version: '3'
services:
  mongodb:
    image: mongo:6.0.2
    container_name: mongodb
    restart: always
    env_file:
      - ../../app.env

    ports:
      - '6000:27017'
    volumes:
      - mongodb:/data/db
      
volumes:
  mongodb: